import { useRef } from 'react';
import Head from 'next/head';
import emailjs from 'emailjs-com';

import Default from '../layouts/Default';
import styles from '../styles/Contact.module.scss';

export default function ContactUs() {
	const form = useRef();

	const sendEmail = (e) => {
		e.preventDefault();

		emailjs
			.sendForm('gmail', 'template_a', form.current, '_iYWkac8R892UoUAV')
			.then(
				(res) => {
					alert(res.text);
				},
				(error) => {
					alert(error.text);
				}
			);
	};

	return (
		<>
			<Head>
				<title>Contact</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.png" />
			</Head>
			<Default>
				<fieldset className={styles.fieldset}>
					<legend className={styles.legend}>Contact</legend>
					<div className={styles.wrapper}>
						<form ref={form} onSubmit={sendEmail} className={styles.form}>
							<div>
								<input
									required
									type="text"
									name="name"
									placeholder="Name"
									className={styles.input}
								/>
								<input
									required
									type="text"
									name="company"
									placeholder="Company"
									className={styles.input}
								/>
							</div>
							<div>
								<input
									required
									type="email"
									name="email"
									placeholder="Email"
									className={styles.input}
								/>
							</div>
							<div>
								<textarea
									required
									name="message"
									placeholder="Message"
									className={styles.textarea}
								/>
							</div>
							<input type="submit" value="Send" className={styles.button} />
						</form>
					</div>
				</fieldset>
			</Default>
		</>
	);
}
