import { useRef } from 'react';
import Head from 'next/head';
import emailjs from 'emailjs-com';
import Default from '../layouts/Default';

export default function ContactUs() {
	const form = useRef();

	const sendEmail = (e) => {
		e.preventDefault();

		emailjs
			.sendForm(
				'gmail',
				'template_a',
				form.current,
				'_iYWkac8R892UoUAV'
			)
			.then(
				(result) => {
					console.log(result.text);
				},
				(error) => {
					console.log(error.text);
				}
			);
	};

	return (
		<>
			<Head>
				<title>Contact</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.png" />
			</Head>
			<Default>
				<form ref={form} onSubmit={sendEmail}>
					<label>Name</label>
					<input required type="text" name="name" />
					<label>Company</label>
					<input required type="text" name="company" />
					<label>Email</label>
          <input required type="email" name="email" />
          <label>Subject</label>
					<input required type="text" name="subject" />
					<label>Message</label>
					<textarea required name="message" />
					<input type="submit" value="Send" />
				</form>
			</Default>
		</>
	);
};
