import Head from 'next/head';
import { FaNode, FaSass } from 'react-icons/fa';
import {
	SiBootstrap,
	SiCss3,
	SiHtml5,
	SiJavascript,
	SiMongodb,
	SiMysql,
	SiNextdotjs,
	SiReact,
	SiTailwindcss,
	SiTypescript
} from 'react-icons/si';

import Default from '../layouts/Default';
import styles from '../styles/Home.module.scss';

export default function Home() {
	return (
		<>
			<Head>
				<title>Patrick Mahloy</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.png" />
			</Head>

			<Default>
				<main className={styles.main}>
					<div className={styles.left}>
						<fieldset className={styles.fieldset}>
							<legend className={`${styles.legend} ${styles.legend_spiel}`}>
								Spiel
							</legend>
							<p className={styles.bio}>
								{`Hi, I'm Patrick. Welcome to my site! I'm a web
                developer and university/bootcamp graduate from Richmond, VA. I
								aspire to build websites and webapps that are enjoyable to
								interact with. What should we build together? 👨🏻‍💻`}
							</p>
						</fieldset>
					</div>
					<div className={styles.right}>
						<fieldset className={styles.fieldset}>
							<legend className={`${styles.legend} ${styles.legend_stack}`}>
								Stack
							</legend>
							<p className={styles.stack}>
								<SiHtml5 className={styles.stack_icon} />
								<SiCss3 className={styles.stack_icon} />
								<SiBootstrap className={styles.stack_icon} />
								<SiTailwindcss className={styles.stack_icon} />
								<br />
								<FaSass className={styles.stack_icon} />
								<SiJavascript className={styles.stack_icon} />
								<SiTypescript className={styles.stack_icon} />
								<SiReact className={styles.stack_icon} />
								<br />
								<SiNextdotjs className={styles.stack_icon} />
								<FaNode className={styles.stack_icon} />
								<SiMysql className={styles.stack_icon} />
								<SiMongodb className={styles.stack_icon} />
							</p>
						</fieldset>
					</div>
				</main>
			</Default>
		</>
	);
}
