import Head from 'next/head';
import { FaNode, FaSass } from 'react-icons/fa';
import {
	SiBootstrap,
	SiCss3,
	SiHtml5,
	SiJavascript,
	SiMongodb,
	SiMysql,
	SiNextdotjs,
	SiReact,
	SiTailwindcss,
	SiTypescript
} from 'react-icons/si';

import Default from '../layouts/Default';
import styles from '../styles/Home.module.css';

export default function Home() {
	return (
		<>
			<Head>
				<title>Patrick Mahloy</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.png" />
			</Head>

			<Default>
				<main className={styles.main}>
					<p className={styles.bio}>
						Hi, I'm Patrick. Welcome to my site! I am a web developer from Richmond, VA and a
						university and bootcamp graduate. I have a background in music and am always looking for new bands to listen to. Recommendations are always welcome!
					</p>
					<div>
						<div className={styles.split}>
							<div className={styles.stack}>
								<p>These are the technologies I use:</p>
								<SiHtml5 className={styles.stack_icon} />
								<SiCss3 className={styles.stack_icon} />
								<SiBootstrap className={styles.stack_icon} />
								<SiTailwindcss className={styles.stack_icon} />
								<br />
								<FaSass className={styles.stack_icon} />
								<SiJavascript className={styles.stack_icon} />
								<SiTypescript className={styles.stack_icon} />
								<SiReact className={styles.stack_icon} />
								<br />
								<SiNextdotjs className={styles.stack_icon} />
								<FaNode className={styles.stack_icon} />
								<SiMysql className={styles.stack_icon} />
								<SiMongodb className={styles.stack_icon} />
							</div>
							<div className={styles.backdrop}>
								<p className={styles.contact}>
									Contact Work Phone: (804) 396-4584 Email:
									patrick.mahloy@gmail.com
								</p>
							</div>
						</div>
					</div>
				</main>
			</Default>
		</>
	);
}
