import Head from 'next/head';
import Default from '../layouts/Default';

import styles from '../styles/Projects.module.scss';

export default function Projects() {
	const imgUrl =
		'https://images.pexels.com/photos/3183150/pexels-photo-3183150.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2';

	return (
		<>
			<Head>
				<title>Projects</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.png" />
			</Head>

			<Default>
				<div className={styles.wrapper}>
					<header className={styles.page_title}>Projects</header>
					<div className={styles.row}>
						<div className={styles.project_summary_wrapper}>
							<fieldset className={styles.fieldset}>
								<legend className={styles.legend_project}>
									All Access Clone
								</legend>
								<p className={styles.project_summary}>
									This project was inspired by a web app I support for my
									current role. I find it do be antiquated, and I wanted a
									bigger project to work on so I challenged myself to recreate
									it (minus the myriad bugs and quirks). My challenge was
									learning how to x, y, z. I overcame these challenges by
									implementing 1, 2, 3. The technologies used for this project
									were <b>React, Tailwind</b>
								</p>
								<div className={styles.button_wrapper}>
									<button className={styles.button}>Demo</button>
									<button className={styles.button}>Source</button>
								</div>
							</fieldset>
						</div>
					</div>
					<div className={styles.row}>
						<div className={styles.project_summary_wrapper}>
							<fieldset className={styles.fieldset}>
								<legend className={styles.legend_project}>
									Project Organizer
								</legend>
								<p className={styles.project_summary}>
									This project was inspired by a web app I support for my
									current role. I find it do be antiquated, and I wanted a
									bigger project to work on so I challenged myself to recreate
									it (minus the myriad bugs and quirks). My challenge was
									learning how to x, y, z. I overcame these challenges by
									implementing 1, 2, 3. The technologies used for this project
									were <b>React, Tailwind</b>
								</p>
								<div className={styles.button_wrapper}>
									<button className={styles.button}>Demo</button>
									<button className={styles.button}>Source</button>
								</div>
							</fieldset>
						</div>
					</div>
					<div className={styles.row}>
						<div className={styles.project_summary_wrapper}>
							<fieldset className={styles.fieldset}>
								<legend className={styles.legend_project}>
									Mortgage Calculator
								</legend>
								<p className={styles.project_summary}>
									This project was inspired by a web app I support for my
									current role. I find it do be antiquated, and I wanted a
									bigger project to work on so I challenged myself to recreate
									it (minus the myriad bugs and quirks). My challenge was
									learning how to x, y, z. I overcame these challenges by
									implementing 1, 2, 3. The technologies used for this project
									were <b>React, Tailwind</b>
								</p>
								<div className={styles.button_wrapper}>
									<button className={styles.button}>Demo</button>
									<button className={styles.button}>Source</button>
								</div>
							</fieldset>
						</div>
					</div>
					<div className={styles.row}>
						<div className={styles.project_summary_wrapper}>
							<fieldset className={styles.fieldset}>
								<legend className={styles.legend_project}>
									Dictionary App
								</legend>
								<p className={styles.project_summary}>
									This project was inspired by a web app I support for my
									current role. I find it do be antiquated, and I wanted a
									bigger project to work on so I challenged myself to recreate
									it (minus the myriad bugs and quirks). My challenge was
									learning how to x, y, z. I overcame these challenges by
									implementing 1, 2, 3. The technologies used for this project
									were <b>React, Tailwind</b>
								</p>
								<div className={styles.button_wrapper}>
									<button className={styles.button}>Demo</button>
									<button className={styles.button}>Source</button>
								</div>
							</fieldset>
						</div>
					</div>
					<div className={styles.row}>
						<div className={styles.project_summary_wrapper}>
							<fieldset className={styles.fieldset}>
								<legend className={styles.legend_project}>
									CLI Calculator
								</legend>
								<p className={styles.project_summary}>
									This project was inspired by a web app I support for my
									current role. I find it do be antiquated, and I wanted a
									bigger project to work on so I challenged myself to recreate
									it (minus the myriad bugs and quirks). My challenge was
									learning how to x, y, z. I overcame these challenges by
									implementing 1, 2, 3. The technologies used for this project
									were <b>React, Tailwind</b>
								</p>
								<div className={styles.button_wrapper}>
									<button className={styles.button}>Demo</button>
									<button className={styles.button}>Source</button>
								</div>
							</fieldset>
						</div>
					</div>
				</div>
			</Default>
		</>
	);
}
